### ISSUE TITLE
preview.grooveshark.com missing

### ISSUE THREAD

**Issue by jomo** [dabido/proxmate.me#2]
related: dabido/ProxMate#21

The [proxy rules](http://api.proxmate.me/package/532d6548f822b20000000001.json) only list these:

```
grooveshark.com
www.grooveshark.com
retro.grooveshark.com
help.grooveshark.com
http://grooveshark.com*
```

---

btw, is the source code for those packages available somewhere?

**Comment by dvcrn** [comment]
Source code is (not yet) available for the packages, but a good idea. I'll see if I can find some time to dump them in a repository. 

I'll add preview.grooveshark.com.

**Comment by jomo** [comment]
:+1:
